name: Build & Deploy Android

on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create release key and release key properties from secrets
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: |
          mkdir keys
          echo -n "${RELEASE_KEYSTORE}" | base64 -d > keys/upload-keystore.jks
          echo "${RELEASE_KEYSTORE_PROPERTIES}" > keys/key.properties
      - name: Test and check code for linting errors
        run: ./gradlew check

      - name: Run build
        run: ./gradlew bundleProdRelease

      - name: Upload build files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: movies-index
          path: |
            app/build/outputs/bundle/prodRelease/app-prod-release.aab
          overwrite: true
          include-hidden-files: true

  deploy-playstore:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: movies-index
          path: artifact
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.sg.moviesindex
          releaseFiles: artifact/app-prod-release.aab
          track: internal