name: Test

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.7
            - uses: actions/setup-java@v4
              with:
                distribution: "temurin"
                java-version: "17"
                cache: gradle
            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
            - name: Create release key properties from secrets
              env:
                RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
              run: |
                mkdir keys
                echo "${RELEASE_KEYSTORE_PROPERTIES}" > keys/key.properties
            - name: Ensure code is properly formatted
              run: ./gradlew lint
            - name: Run tests
              run: ./gradlew test
